# Generated by Django 5.2.3 on 2025-07-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search_song',
        ),
    ]
