# Generated by Django 5.2.3 on 2025-07-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Search', '0002_delete_search_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField()),
                ('song_name', models.CharField(max_length=100)),
                ('singers_name', models.CharField(max_length=100)),
                ('lyric', models.CharField(max_length=1000)),
            ],
        ),
    ]
