# Generated by Django 5.2.3 on 2025-07-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongList',
            new_name='song_list',
        ),
    ]
