# Generated by Django 5.2.3 on 2025-07-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_rename_songlist_song_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='song_list',
        ),
    ]
