# Generated by Django 5.2.3 on 2025-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=30)),
                ('singer_id', models.IntegerField()),
                ('singer_abstract', models.CharField(max_length=300)),
                ('songs_id', models.JSONField(default=list)),
            ],
        ),
    ]
