# Generated by Django 5.2.3 on 2025-07-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SingerInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SingerInfo',
            new_name='singer_info',
        ),
    ]
