# Generated by Django 5.2.3 on 2025-07-04 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SingerInfo", "0002_rename_singerinfo_singer_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="singer_info",
            old_name="songs_id",
            new_name="songs",
        ),
    ]
