# Generated by Django 5.2.3 on 2025-07-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SongInfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song_info",
            name="lyric",
            field=models.CharField(max_length=1000),
        ),
    ]
