# Generated by Django 5.2.3 on 2025-07-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SongInfo", "0002_alter_song_info_lyric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song_info",
            name="comments",
            field=models.JSONField(default=list),
        ),
    ]
